# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://internationaltradeadministration.github.io/select-usa/
title: SelectUSA
description: > # "Write an awesome description for your new site here. 
  SelectUSA seeks to highlight the many advantages the United States offers as a location for business and investment. 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

